#!/bin/bash

#> [app]=batch-cs [version]=4.1.607 [profile]=eks

JAR_FILE=$(aws s3 ls wa-devops-s/kda/im/compliance-app/${APP,,}/imqa/ | grep -e "-$VERSION-SNAPSHOT-" | sort | head -n 1 | awk -F ' ' '{print $4}')
if [ -z $JAR_FILE ]; then
  echo "No jar files found"
  exit 1
fi

YAML_FILE=~/configs/${APP,,}/$PROFILE.yaml
if [ ! -f $YAML_FILE ]; then
  echo "Profile [$PROFILE] not found in $YAML_FILE"
  exit 1
fi

echo Downloading "$JAR_FILE"
aws s3 cp s3://wa-devops-s/kda/im/compliance-app/${APP,,}/imqa/$JAR_FILE .

OUT_FILE=${APP,,}-$VERSION-$PROFILE.jar
echo Building $OUT_FILE

cp $YAML_FILE application.yml
zip -u $JAR_FILE application.yml
mv $JAR_FILE $OUT_FILE
rm application.yml
