#!/usr/bin/env python3

from rsa import generate_key, encrypt, decrypt

secret_key = generate_key("hey")
private_key = secret_key.exportKey("PEM")

with open("priv_rsa", "wb") as priv_file:
  priv_file.write(private_key)
