#!/usr/bin/env python3

import sys
from rsa import generate_key, encrypt, decrypt

seed = sys.argv[1]
filename = sys.argv[2]
secret_key = generate_key(seed)
private_key = secret_key.exportKey("PEM")

with open(filename, "wb") as priv_file:
  priv_file.write(private_key)
