#!/bin/bash

SNIP=${1}-${2}

usage() {
  echo "Usage: sn $SNIP"
  echo "Params:"
  for key in ${!VAR[@]}; do
    echo "  --$key"
  done
  exit 1
}

eval "declare -A VAR=($(mc cat pi/snip/$SNIP | grep '#> ' | cut -c 4-))"

LONG="help"
for key in ${!VAR[@]}; do
  LONG="$LONG,${key}:"
done

ARGS=$(getopt --long $LONG -- "$@");
code=$?
if (( code > 0 )); then
  usage
fi

eval set -- ${ARGS}

while [[ $# -gt 0 ]]; do
  if [[ "$1" == "--" ]]; then
    i=1
    while [[ $# -gt 0 ]]; do
      eval "export P$i=$2"
      ((i=i+1))
      shift
    done
  else
    V=${1:2}
    VAR[$V]=$2
    shift 2
  fi
done

KNOWN_VARS=""
for key in ${!VAR[@]}; do
  VNAME=${key^^}
  eval "export $VNAME=${VAR[$key]}"
  KNOWN_VARS="$KNOWN_VARS $VNAME"
done

bash <(mc cat pi/snip/$SNIP | envsubst "$KNOWN_VARS")

#mc cat pi/snip/$SNIP | envsubst
