#!/bin/bash

SNIP=$1

usage() {
  echo "Usage: sn $SNIP"
  echo "Params:"
  for key in ${!VAR[@]}; do
    echo "  --$key"
  done
  exit 1
}

eval "declare -A VAR=($(mc cat pi/snip/$SNIP | grep '#> ' | cut -c 4-))"

LONG="help"
for key in ${!VAR[@]}; do
  LONG="$LONG,${key}:"
done

ARGS=$(getopt --long $LONG -- "$@");
code=$?
if (( code > 0 )); then
  usage
fi

eval set -- ${ARGS}

while [[ $# -gt 0 ]]; do
  if [[ "$1" == "--" ]]; then
    i=1
    while [[ $# -gt 0 ]]; do
      eval "export P$i=$2"
      ((i=i+1))
      shift
    done
  else
    V=${1:2}
    VAR[$V]=$2
    eval "export ${V^^}=${VAR[$V]}"
    shift 2
  fi
done

mc cat pi/snip/$SNIP | envsubst | bash
