#!/bin/bash

if [[ $# -lt 2 ]]; then
  usage
fi

COMMAND=$1; shift

ARGS=$(getopt -o c:m:d: --long cpu:,mem:,disk: -- "$@")
eval set -- ${ARGS}


# -- VM CREATE

vm_create() {
ARGS=$(getopt -o c:m:d: --long cpu:,mem:,disk: -- "$@"); eval set -- ${ARGS}
declare -A PARAMS='([cpu]="2" [mem]="2GB" [disk]="20GB")'

while [[ $# -gt 0 ]]; do
  case $1 in
    -c | --cpu)  PARAMS[cpu]=$2; shift 2 ;;
    -m | --mem)  PARAMS[mem]=$2; shift 2 ;;
    -d | --disk) PARAMS[disk]=$2; shift 2 ;;
    -- ) VM=$2; shift 2 ;;
  esac
done

echo "Creating vm $VM"
echo "cpu = ${PARAMS[cpu]}"
echo "mem = ${PARAMS[mem]}"
echo "disk = ${PARAMS[disk]}"

lxc init ubuntu:22.04 ${VM} --vm
lxc config set ${VM} limits.cpu ${PARAMS[cpu]}
lxc config set ${VM} limits.memory ${PARAMS[mem]}
lxc config device override ${VM} root size=${PARAMS[disk]}
lxc start ${VM}

}


function usage {
cat <<EOF
  Usage:  vm command scope [ARGS]
EOF
exit 1
}

eval vm_${COMMAND} "$@"
