#!/bin/bash
#> [ns]=default

CLUSTER=$(cat ~/.config/cluster)
echo "Deleting Flink cluster in EKS [$CLUSTER]. Using namespace [$NS]."

FOLDER=~/.config/$CLUSTER/$NS

kubectl delete -n $NS -f $FOLDER/flink-configmap.yaml
kubectl delete -n $NS -f $FOLDER/flink-jobm-deployment.yaml
kubectl delete -n $NS -f $FOLDER/flink-taskmanagers-deployment.yaml
kubectl delete -n $NS -f $FOLDER/flink-jobm-loadbalancer.yaml
