#!/bin/bash

#> [ns]=tools

kubectl create ns $NS
cat<<EOF | kubectl apply -n $NS -f -
apiVersion: v1
kind: ConfigMap
metadata:
  name: admin-init-script
data:
  init-script.sh: |
    #!/bin/bash
    apt update
    apt install -y nano curl jq iputils-ping dnsutils openjdk-11-jre wget
    wget -P /root https://archive.apache.org/dist/flink/flink-1.13.6/flink-1.13.6-bin-scala_2.11.tgz
    cd /root
    tar xzvf flink-1.13.6-bin-scala_2.11.tgz
    rm flink-1.13.6-bin-scala_2.11.tgz
    sleep 365d
EOF


cat <<EOF | kubectl apply -n $NS -f -
apiVersion: v1
kind: Pod

metadata:
  name: admin
  labels:
    app: admin

spec:
  containers:
  - name: admin
    image: ubuntu:latest
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: script-volume
      mountPath: /script
    command: ["/script/init-script.sh"]
  volumes:
  - name: script-volume
    configMap:
      name: admin-init-script
      defaultMode: 0744
  restartPolicy: Always
EOF


