#!/bin/bash

#> [ns]=cert-manager

helm repo add jetstack https://charts.jetstack.io
helm repo update
helm upgrade --install cert-manager jetstack/cert-manager \
  --set installCRDs=true --namespace $NS  --create-namespace
