#!/bin/bash

#> [ns]=redis

helm repo add bitnami https://charts.bitnami.com/bitnami
helm repo update
helm install redis bitnami/redis -n $NS --create-namespace

#kubectl scale --replicas=3 deployment/redis -n $NS

export REDIS_PASSWORD=$(kubectl get secret --namespace $NS redis -o jsonpath="{.data.redis-password}" | base64 -d)
kubectl run --namespace $NS redis-client --restart='Never'  --env REDIS_PASSWORD=$REDIS_PASSWORD \
 --image docker.io/bitnami/redis:7.0.12-debian-11-r2 --command -- sleep infinity
