#!/bin/bash

#> [ns]=splunk [cluster]=eks-flink-sandbox

helm repo add splunk-otel-collector-chart https://signalfx.github.io/splunk-otel-collector-chart
helm repo update

helm install splunk-collector --namespace $NS --create-namespace \
 --set="cloudProvider=aws,distribution=eks,splunkObservability.accessToken=OTCm75WvBf57te0v8UO6ew,clusterName=$CLUSTER,splunkObservability.realm=us1,gateway.enabled=false,splunkObservability.profilingEnabled=true" \
 splunk-otel-collector-chart/splunk-otel-collector
