#!/bin/bash

#> [CLUSTER]=$DEF_CLUSTER

SG_ID=`aws eks describe-cluster --name $CLUSTER | jq -r '.cluster.resourcesVpcConfig.clusterSecurityGroupId'`
echo "Using security group $SG_ID"

aws ec2 authorize-security-group-ingress \
  --group-id $SG_ID \
  --ip-permissions "[ \
                      { \
                        \"IpProtocol\": \"tcp\", \
                        \"FromPort\": 30081, \
                        \"ToPort\": 30081, \
                        \"IpRanges\": [{\"CidrIp\": \"0.0.0.0/0\"}] \
                      }, \
                      { \
                        \"IpProtocol\": \"tcp\", \
                        \"FromPort\": 30082, \
                        \"ToPort\": 30082, \
                        \"IpRanges\": [{\"CidrIp\": \"0.0.0.0/0\"}] \
                      }, \
                      { \
                        \"IpProtocol\": \"tcp\", \
                        \"FromPort\": 31644, \
                        \"ToPort\": 31644, \
                        \"IpRanges\": [{\"CidrIp\": \"0.0.0.0/0\"}] \
                      }, \
                      { \
                        \"IpProtocol\": \"tcp\", \
                        \"FromPort\": 31092, \
                        \"ToPort\": 31092, \
                        \"IpRanges\": [{\"CidrIp\": \"0.0.0.0/0\"}] \
                      } \
                    ]"
